apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - name: http
      port: 80
      targetPort: 80
      # Pick a convenient NodePort (30000â€“32767) or omit for random
      nodePort: 30080

