apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
    - name: http
      port: 5173
      targetPort: 80
